### ISSUE TITLE
unified API for documentStore and blobStorage

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-core#11]
this issue serves to document some thoughts about a unified API for `documentStore` and `blobStorage`:

it is desired that both objects have the same interface so it would be easy to remember for extensions authors.

to do this i think we would need the following changes:

- move repetitive code to core, you can see that in some store implementations we are doing some repetitive tasks ([1](https://github.com/jsreport/jsreport-fs-store/blob/master/lib/fsStore.js#L23), [2](https://github.com/jsreport/jsreport-mongodb-store/blob/master/lib/provider.js#L51), [3](https://github.com/jsreport/jsreport-fs-store/blob/master/lib/fsStore.js#L219), [4](https://github.com/jsreport/jsreport-mongodb-store/blob/master/lib/provider.js#L153)) and i think that **we can centralize that code to an interface that just delegate calls to a particular provider implementation (let's call it the main `documentStore` interface)**, then extensions authors will just need to implement **a provider interface with just the relevant logic for that particular implementation, nothing more, nothing less** (a function constructor with standard methods of a store provider, like init,  drop and find, insert, update, etc for collections), with this change i'm sure that we will drop some code and end with a clean interface.
- all supported methods for a `documentStore` implementation should be defined first in the **main `documentStore` interface**, this means that our **main interface** should have `init, drop` and  `find, insert, count, update, etc for collections` declared in way that just delegate the job to the current provider implementation. All hooks/listeners should be called from our **main interface** not inside provider implementations, this will allow extensions to only do its real job instead of caring about invoking listeners/hooks and we will benefit from that because we will have all of this logic centralized in core.
```js
DocumentStoreCollection.prototype.insert = function (doc, req) {
  var self = this
  // call hooks from main interface
  return this.beforeInsertListeners.fire(doc, req).then(function () {
    // delegate to provider implementation
    return self._provider.insert(doc)

    // we can even take advantage of this to improve error messages when a store extension doesn't implement something
    /*
    if (typeof self._provider.insert !== 'function') {
      // log a warning or throw an error
     throw new Error('store ' + self._provider.name + ' extension doest not support insert method')
    }
    
    return self._provider.insert(doc)
    */
  })
}
```
- we can register a provider implementation (fs-store, mongodb, etc) in the **main `documentStore` interface** using the good [old](https://github.com/jsreport/jsreport-fs-store/blob/master/lib/main.js#L24) [assignment](https://github.com/jsreport/jsreport-mongodb-store/blob/master/lib/main.js#L32) or maybe we can take the opportunity to create a new method `registerProvider`, the later would have the benefit to implement some hooks and do something (probably logging) when an extension is registering a provider implementation, later we can think more use cases for this hook.
- we should model our new `blobStorage interface` based on the same principles of the `main documentStore interface`, delegate calls to provider implementations, implement and call hooks from the `main blobStorage interface`, rename `write`, `read`, `remove` to `insert, find, remove` and maybe add new methods like `init, count, etc`.

and of course all of these things will require that maybe we need to add more extension points in order to achieve a general interface and ready for any store implementation.

this is what i have until now in my head, hope that everything is clear 😄

**Comment by pofider** [comment]
> move repetitive code to core, you can see that in some store implementations we are doing some repetitive tasks (1, 2, 3, 4) and i think that we can centralize that code to an interface that just delegate calls to a particular provider implementation 

Yes, that is very obvious. Lets do that

> all supported methods for a documentStore implementation should be defined first in the main documentStore interface

Yes, that is basically the same as previous point

> we can register a provider implementation (fs-store, mongodb, etc) in the main documentStore interface using the good old assignment or maybe we can take the opportunity to create a new method registerProvider

Yes, registerProvider would nicely fit to the existing registerEntityType and others

> we should model our new blobStorage interface based on the same principles of the main documentStore interface

Yes

I believe that we don't need more to analyse here.

**Comment by pofider** [comment]
Implemented in v2
