### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by atrauzzi** [jsreport/jsreport-core#12]
Would love to see first-party TS definitions offered!

**Comment by pofider** [comment]
Thank you for suggestion. We're too busy to do it right now, but we will keep it here and hopefully get to it one day.

The PR is welcome for this of course.

**Comment by taoqf** [comment]
see https://github.com/jsreport/jsreport-core/pull/26

**Comment by taoqf** [comment]
@atrauzzi  @types/jsreport-core is ready to use.

**Comment by LukeBillo** [comment]
Just a heads up - this seems to be resolved, because I've used the Typescript definitions recently.

Thanks @taoqf 👍 :)

**Comment by pofider** [comment]
I pushed some additional extensions to the DefinitelyTyped.
Also included a note about typescript to the readme.
And blogged about it [here](https://jsreport.net/blog/pdf-in-typescript).

The types aren't finished, but it's in a good way.
I will in time add more types.
Big thank you to the @taoqf for the original contribution.
