### ISSUE TITLE
How to execute in aws lambda?

### ISSUE THREAD

**Issue by brucemackenzie** [jsreport/jsreport-core#29]
I'm having trouble getting PDF generation working in an aws-lambda environment (works fine on a Mac laptop).

From what I can tell so far, this is largely because of various `jsreport-***` modules/extensions attempting to write into places other than the folder specified in the `options:tempDirectory` folder. There is only one writable folder in a nodeJS lambda environment so these attempts fail.
I'm working around this by copying the entire `data/` subtree into the writable area `/tmp` which seems to help.
My latest issue is with the extension loading logic. I've disabled discovery and I'm explicitly `use`ing the modules I need but I'm still seeing something in the `jsreport-core/lib/extensions/extensionManager.js` failing with this message:

> error: Error when loading extension Error: ENOENT: no such file or directory, scandir '/var/runtime/node_modules/awslambda/node_modules'

I've found one more option whose use is unclear to me but appears to be used in the extension loading logic: `parentModuleDirectory`. I'm going to experiment with that to see what it does.

Any help/suggestions appreciated.

**Comment by bjrmatos** [comment]
hi! can you show the code that you are using to start jsreport (the entry point file)?

**Comment by brucemackenzie** [comment]
options:
`
{
    "certificate": {
        "key": "certificates/jsreport.net.key",
        "cert": "certificates/jsreport.net.cert"
    },
    "authentication": {
        "cookieSession": {
            "secret": "<your strong secret>"
        },
        "admin": {
            "username": "admin",
            "password": "password"
        },
        "enabled": false
    },
    "httpPort": 5488,
    "httpsPort": null,
    "logger": {
        "error": {
            "transport": "console",
            "level": "error"
        }
    },
    "blobStorage": "inMemory",
    "tempDirectory": "/tmp",
    "dataDirectory": "/tmp/jsreport/data",
    "rootDirectory": "/var/task",
    "phantom": {
        "strategy": "dedicated-process",
        "timeout": 60000
    },
    "tasks": {
        "strategy": "dedicated-process",
        "timeout": 10000,
        "allowedModules": "*"
    },
    "scripts": {
        "allowedModules": [],
        "timeout": 60000
    },
    "sample-template": {
        "createSamples": true
    },
    "connectionString": {
        "name": "fs",
        "syncModifications": false
    },
    "discover": false,
    "autoTempCleanup": false,
    "parentModuleDirectory": "/tmp"
}
`
code:
`
	const jsreport = require('jsreport-core')(config);
	jsreport.use(require('jsreport-assets')())
	jsreport.use(require('jsreport-data')())
	jsreport.use(require('jsreport-fs-store')())
	jsreport.use(require('jsreport-handlebars')());
	jsreport.use(require('jsreport-html-to-xlsx')())
	jsreport.use(require('jsreport-images')())
	jsreport.use(require('jsreport-phantom-pdf')())
	jsreport.use(require('jsreport-scripts')())
	jsreport.use(require('jsreport-templates')())
	jsreport.use(require('jsreport-text')())

	return jsreport.init()
	.then(function() {
		console.log('Starting …')
		return jsreport.render({
			template: { shortid: options.templateID },
			data: options.data,
		})
		.then(function(res) {
			return res.content
		})
		.catch(function(e) {
			return Promise.reject(e)
		})
	})
	.catch(function(e) {
		return Promise.reject(e)
	})
`
It this is not a supported scenario I can switch to using an ec2 instance with fewer constraints.
Was just looking to keep with lambdas if possible.

**Comment by brucemackenzie** [comment]
Thanks so much for the detailed response.
I'll get back to you with more details as I know them. It's good to know that someone else has made this work. That helps me :)

**Comment by brucemackenzie** [comment]
BTW I got around the PhantomJS compile issue with Docker:
https://medium.freecodecamp.org/escaping-lambda-function-hell-using-docker-40b187ec1e48

**Comment by pofider** [comment]
I published an article on how to use jsreport in aws lambda.

https://jsreport.net/learn/aws-lambda-serverless
