### ISSUE TITLE
default to development mode

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-core#3]
just to keep track what we have discussed in [other comments](https://github.com/jsreport/jsreport-core/commit/d5a026932a00a208678ca728edce57c616ccffa2)

**Comment by pofider** [comment]
**jsreport-core**
- change the default mode in jsreport-core to development

- very clearly note in the logs which NODE_ENV we are starting in and if (which) configuration file is applied

**jsreport**

- change the installation instructions

PRODUCTION INSTALLATION
```sh
npm install --production
npm start --production
```

DEVELOPMENT INSTALLATION
```sh
npm install
npm start
```

The users with existing `prod.config.json` likely won't get the expected configuration but I guess it will be very visible from the log that the development environment is applied and especially the port is different. I guess it is not big problem.

**Comment by pofider** [comment]
This should be ready now. As said in the comment, the change is not that dramatic, we can include it in the 0.12

**Comment by bjrmatos** [comment]
excellent!
