### ISSUE TITLE
Table headers are overlapping with text

### ISSUE THREAD

**Issue by meckharr** [jsreport/jsreport-core#30]
We have a problem with table headers, sometimes the tables headers on the next page are wrong.

First the header on the next page look like this:
![image](https://user-images.githubusercontent.com/21262099/37826871-7ce89d2c-2e95-11e8-995a-4294f7c87854.png)

After i add following style:
`table tr {
    overflow:hidden;
}`
it looks like this:
![image](https://user-images.githubusercontent.com/21262099/37827029-10a859bc-2e96-11e8-8ada-576b2f3ce5b8.png)

However, both variants are wrong.

**Comment by pofider** [comment]
Please take a look here.
https://github.com/jsreport/jsreport/issues/93
