### ISSUE TITLE
avoid using shared instance of winston

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-core#35]
right now we use the default winston instance that is shared for any package that use winston in the same process, this can be a problem when an app uses winston by itself. however it is true that we somehow workaround the problem by saving a [logger with "jsreport" key](https://github.com/jsreport/jsreport-core/blob/master/lib/reporter.js#L542) but a common problem when developing and running tests is that we need [some cleanup logic](https://github.com/jsreport/jsreport-core/blob/master/test/reporterTest.js#L37) to ensure that we can use the logger safely when using multiple jsreport instance in the same process (something we do frequently in tests) after [changing some logger functions](https://github.com/jsreport/jsreport-scripts/blob/75da25f98f32b0368afeec5fc8f2361e853aa559/test/scriptsTest.js#L739).

i don't know a good reason to avoid having a custom winston instance per jsreport instance, it makes sense to do it and will make the usage of multiple jsreport instances in a process safe to use and without side effects.

**Comment by pofider** [comment]
This will be done as part of the https://github.com/jsreport/jsreport/issues/723
Closing it here as duplicated.
