### ISSUE TITLE
Found vulnerabilities

### ISSUE THREAD

**Issue by jagdeep-anetcorp** [jsreport/jsreport-core#37]
=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Regular Expression Denial of Service

  Package         string

  Patched in      No patch available

  Dependency of   jsreport

  Path            jsreport > jsreport-core > script-manager > string

  More info       https://nodesecurity.io/advisories/536

**Comment by pofider** [comment]
https://github.com/jsreport/jsreport/issues/354#issuecomment-377030562
