### ISSUE TITLE
Analyse if passing request object to store functions shouldn't be required

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport-core#39]
```js
reporter.documentStore.collection('foo').find({}, req?)
```

It is not required to pass the `req` object currently.
This is error prone as devs can forget it.

I would propose to change it and make `req` object parameter required.
In cases when it does make really sense to pass it without, dev should make it explicit.
Something like
```js
reporter.documentStore.collection('foo').findWithoutContext({})
```

**Comment by pofider** [comment]
I guess we learned to live with it. There are still calls that need a request like samples creations, scheduling, logs flush.
@bjrmatos I would close this, what you think?

**Comment by bjrmatos** [comment]
for the moment yes, i guess we can live with it not being required, we were always able to handle the case just fine
