### ISSUE TITLE
Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by mk48** [jsreport/jsreport-core#44]
Do i have to install puppeteer also to use jsreport-core?

**package.json**
```
"jsreport-chrome-pdf": "^1.3.0",
"jsreport-core": "^2.4.1",
"jsreport-handlebars": "^2.0.1",
```

**My Code**
I just copied this code from homepage of this github page
```
var express = require('express');
var router = express.Router();
const jsreport = require('jsreport-core')();

router.get('/test', function(req, res, next) {
   
    jsreport.init().then(() => {
        return jsreport.render({
            template: {
                content: '<h1>Hello {{foo}}</h1>',
                engine: 'handlebars',
                recipe: 'chrome-pdf'
            },
            data: {
                foo: "world"
            }
        }).then((resp) => {
             // prints pdf with headline Hello world
            console.log(resp.content.toString())
         });
    }).catch((e) => {
        console.error(e)
    })
});


module.exports = router;

```

![image](https://user-images.githubusercontent.com/3082469/53723799-850cd680-3e8e-11e9-9d98-43521a9efab9.png)

**Comment by pofider** [comment]
You need to install puppeteer to be able to use jsreport-chrome-pdf extension.

**Comment by mk48** [comment]
Thanks, 

Also, we have to update the below section in Readme

![image](https://user-images.githubusercontent.com/3082469/53779899-02d0f080-3f28-11e9-9619-9768dbd8edbc.png)

**Comment by bjrmatos** [comment]
@mk48 README has been updated. thanks

**Comment by yami12376** [comment]
I am doing steps from: https://jsreport.net/learn/centos
but i get an error:

jsreport start

> An error has occurred when trying to initialize jsreport (2). Error when loading extension chrome-pdf
> Error: Cannot find module 'puppeteer'
