### ISSUE TITLE
pdfOperations merge not working

### ISSUE THREAD

**Issue by robindijkhof** [jsreport/jsreport-core#50]
I was playing with the API example from [here](https://jsreport.net/learn/pdf-utils).

```
{
  "template": {
    "content": "Main Template",
    "recipe": "chrome-pdf",
    "engine": "handlebars",
    "chrome": {
      "marginTop": "50px"
    },
    "pdfOperations": [{
      "template": {
        "content": "Header",
        "recipe": "chrome-pdf",
        "engine": "handlebars"
      },
      "type": "merge"
    }]
  }
}
```

Unfortunately, "Header" is not merged and the final result only displays "Main Template"

I'm using the following dependencies:
handlebars: 4.5.3
jsreport-chrome-pdf: 1.6.1
jsreport-core: 2.6.2
jsreport-handlebars: 2.1.0

**Comment by bjrmatos** [comment]
if you are using core, you need to install also the jsreport-pdf-utils dependency.
