### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by LubomirIgonda1** [jsreport/jsreport-core#52]
Hi I found weird behaviour jsreport cache in my project. In some cases it create memory leak here is pic

![90685112-9bb51200-e269-11ea-8afe-98cf2a060342](https://user-images.githubusercontent.com/9303146/90726749-84eed980-e2c2-11ea-8c17-25d8a4c73423.png)

1. snapshot is pure started server
2. snapshot is after render 1. PDF
3. snapshot is after render 2. PDF with diff template data
4. snapshot is after render 2. PDF

memory stack trace is comparision between 4. and 3. snapshot almost comparision looks diff 3. and 2, 2. and 1.

after every render memory increase by a new cache key but GC never release that memory.
My project in production after 2 days has more than 1.5 GB

I try to disable template cache but witout any success.

When I trying to figure out this issue I observed that if i try to render PDF with the same data it ok and jsreport use the cache but if i try to render the same PDF with different template data then jsreport create a new cache object witch GC never release.

Olso I try to setup diff options for lru-cache that you use for caching but nothing changed

here is test repo https://github.com/LubomirIgonda1/jsreport-memory-leak-example/tree/master

thanks for any help

    ENV:
    node 10.16.0
    "jsreport-assets": "1.6.0",
    "jsreport-chrome-pdf": "1.8.0",
    "jsreport-core": "2.9.0",
    "jsreport-ejs": "2.2.0",
    "jsreport-pdf-utils": "1.8.0",

    // CONFIG
    jsreport: <IJsReportConfig>{
		config: {
			templatingEngines: {
				strategy: 'in-process',
				templateCache: {
					enabled: false
				}
			},
			extensions: {
				'chrome-pdf': {
					launchOptions: {
						args: ['--no-sandbox']
					}
				},
				assets: {
					searchOnDiskIfNotFoundInStore: true,
					allowedFiles: '**/*.*'
				}
			}
		},
		render: {
			engine: 'ejs',
			recipe: 'chrome-pdf',
			chrome: {
				marginTop: '2.5cm',
				marginRight: '2.5cm',
				marginBottom: '2.5cm',
				marginLeft: '2.5cm'
			}
		}
	}

**Comment by pofider** [comment]
Thank you, we take a look on the repo.

**Comment by pofider** [comment]
The cache builds key from the template.content.
Your architecture/code is running the ejs upfront before the jsreport.render is called and builds dynamic template.content.
Therefore the cache size increases to a maximum of 100 items because `template.content` is different.
However,  even this still shouldn't be an issue. 
I see that my memory consumptions reach 1.5GB, but after forcing the gc, it falls down.

You can disable cache this way.
```js
const jsReportConfig = {
	config: {
		templatingEngines: {
			strategy: 'in-process',
			templateCache: {
				enabled: false
			}
		},
...
```

If you want to experiment, you can pass to the templateCache prop other configurations used by [lru-cache](https://github.com/isaacs/node-lru-cache) package.

I recommend forcing gc using `global.gc()` during experiments, because nodejs isn't very eager to call gc even there is 1.5GB in use.

**Comment by pofider** [comment]
I am closing this, but feel free to add comments, it's still monitored.

**Comment by LubomirIgonda1** [comment]
Hi @pofider I already try to disable cache but it looks like it is not working here is some screenshot how memory increase and than debugger stop the code as a prevent out of memory crash. I added to my test repozitory manual trigger GC in the endpoint /render and set templateCache enabled to false as you mentioned but result is still the same. It looks like lru-cache ignore the maximum items


![image](https://user-images.githubusercontent.com/9303146/91167723-bad1fa80-e6d4-11ea-996a-687c9c479c47.png)
![image](https://user-images.githubusercontent.com/9303146/91167737-c45b6280-e6d4-11ea-8e48-0761c1616a90.png)

**Comment by pofider** [comment]
I believe your snapshots are still before the gc has run.
The trouble is that even calling explicit gc doesn't need to force nodejs to run it immediately.
I don't know the theory but this is how I experience it.

Please try this test
```js
const axios = require('axios')

function run() {
    return axios.get('http://localhost:4000/render')
}

async function runMany() {
    for (let i = 0; i < 1000000000; i++) {
        await run()
        console.log(i)
    }
}

runMany().catch(console.error)
```

I have nodejs 12, I run it an hour. The memory goes up to ~2GB and then falls down to the 200mb. Then go up again to the 2GB and falls down. Even I have your repo and call gc after every run. I can render to 1000 report and don't see any memory errors. It is just nodejs too lazy to really run the gc.

What you can do also to verify the hypothesis is to change your run script to this:

```
"start": "cross-env TS_NODE_FILES=true NODE_ENV=development NODE_OPTIONS=--max-old-space-size=200 node --expose-gc --inspect -r ts-node/register src/index.ts"
```

This time I limit the memory to max 200mb. And I render 200 reports and the memory is still ~200mb consumption. This make nodejs less lazy to really process gc.

**Comment by LubomirIgonda1** [comment]
Ok I think that I figured out what was the problem. After running stres test code I try to update node version from 10.21.0 to 12.18.3 and the memory leak disappeared so the issue was the versio of node js I guess. Thanks for help

**Comment by pofider** [comment]
You are welcome. Thank you for preparing the test repo.
