### ISSUE TITLE
update winston dependency for compatibility with Node 14

### ISSUE THREAD

**Issue by dlong500** [jsreport/jsreport-core#53]
There is a winston 2.4.5 release that addresses some issues with Node 14.  That's a very minor version bump from the current 2.4.4 that should not cause any breaking changes.  Can we get a release with that upgraded dependency?  I can make a PR but it might be easier on your process side to just bump that single dependency.

**Comment by dlong500** [comment]
@pofider I understand that you plan to have a major winston upgrade for jsreport-core v3, but in the mean time I believe the minor update to winston v2.4.5 (from 2.4.4) would resolve the Node 14 compatibility issue.

**Comment by pofider** [comment]
@dlong500 Thank you for the notice, we didn't know there is such fix. The Winston is now upgraded to the 2.4.5 as suggested.

**Comment by pofider** [comment]
@dlong500 Unfortunately we didn't add it to the jsreport 2.10.0. So it's just in the latest jsreport-core@2.10.1 for now.
